nexus-react/package-lock.json, nexus-react/package.json, nexus-react/src/components/Auth/index.js, nexus-react/src/components/Auth/store/actions.js, nexus-react/src/components/Instance/Links.jsx, nexus-react/src/components/Shapes/Distribution.js, nexus-react/src/components/Shapes/ImageAttachment.jsx, nexus-react/src/components/Shapes/Preview.jsx, nexus-react/src/components/Shapes/Relationship.js, nexus-react/src/components/Shapes/TextAttachment.jsx, nexus-react/src/components/Shapes/index.js
This adds two new components, the TextAttachment and ImageAttachment Shapes which can be used to load images or raw text files to preview in a thumbnail. The TextAttachment so far just shows a file icon, but only because I thought it was more interesting to see than the data I found using raw text so far. 
Previously attachments were broken because images were being called without Bearer tokens, now they're being read and put into the dom with inline base64 data.
=> fix previews and image loading for attachments

nexus-react/package-lock.json, nexus-react/package.json, nexus-react/src/components/Auth/store/actions.js
We only supported plain base64 payload, while JWT uses base64url, which differs by 2 characters.
If the JWT payload contains one of these 2 characters, it would fail to decode.
This commit adds proper support for base64url
=> Support base64url encoding from JWT in Auth.

nexus-sdk-js/README.md, nexus-sdk-js/package-lock.json, nexus-sdk-js/package.json, nexus-sdk-js/src/Nexus.ts, nexus-sdk-js/src/Organization.ts, nexus-sdk-js/src/utils/http.ts, nexus-sdk-js/tsconfig.json, nexus-sdk-js/tslint.json
fixes BlueBrain/nexus#296
You can now `import Nexus from 'nexus-sdk'` in an es project, or `require('nexus-sdk')` in a commonjs project.
The SDK is now universal (works in both Node and browser) thanks to `node-fetch`.
I've implemented a temporary `listOrgs` method as well.
=> Integrate to nexusweb as dependency

nexus-sdk-js/package.json
'prepublish' is deprecated. Replaced by 'prepublishOnly'.
=> Fix name of prepublishOnly npm script

nexus-sdk-js/src/Resource/__tests__/Resource.spec.ts, nexus-sdk-js/src/Resource/index.ts
Adds a `name` getter to Resource
It's needed for human-readable interfaces, as a way for us to reference resources without looking at UUIDs
You can overwrite the `formatName` property to create your own UI-friendly Resource name, but the default behavior follows @MFSY's advice on where to get a semantically useful resource label for UI purposes.
=> add resource name property and tests

nexus-sdk-js/package-lock.json, nexus-sdk-js/package.json, nexus-sdk-js/src/Project/index.ts, nexus-sdk-js/src/Resource/index.ts, nexus-sdk-js/src/Resource/utils.ts
Fixes https://github.com/BlueBrain/nexus-explorer/pull/84
`Promise.all` returns everything or nothing. So because some resources return a 404 the whole thing was crashing.
I've made sure we handle errors a little better, return `Promise.resolve(undefined)` when there is a problem fetching a resource and finally filter out undefined resources. 
Also, I'm pointing at the static method `Resource.list` as there was some code duplication.
=> fix fetching all resources issue

nexus-sdk-js/package-lock.json, nexus-sdk-js/package.json
Looks like it works with 0.1.7 now. So apparently, the package-lock file need to be in sync, otherwise NPM does not complain, but everything is screwed. Might be a bug.
=> publishing 0.1.7 as 0.1.6 seems to have crashed somehow

nexus-sdk-js/package-lock.json, nexus-sdk-js/package.json, nexus-sdk-js/src/Organization/index.ts, nexus-sdk-js/src/Organization/types.ts, nexus-sdk-js/src/Organization/utils.ts, nexus-sdk-js/src/Project/index.ts, nexus-sdk-js/src/Project/types.ts, nexus-sdk-js/src/Project/utils.ts, nexus-sdk-js/src/utils/events.ts
SO, you can now subscribe to Org and Project events:
```typescript
const eventSource = Project.subscribe({
onProjectCreated: (projectCreated) => /* do whatever you want */,
onProjectUpdated: (projectCreatedEvent) => /* ... */,
onProjectDeprecated: (projectDeprecated) => /* ... */,
})
```
and the same for organisations:
```typescript
const eventSource = Organization.subscribe({
onOrgCreated: (projectCreated) => /* do whatever you want */,
onOrgUpdated: (projectCreatedEvent) => /* ... */,
onOrgDeprecated: (projectDeprecated) => /* ... */,
})
// when your done
eventSource.close()
```
That means we can integrate this to nexus-web and get live notifications
=> Orgs and Projects events source

nexus-sdk-js/src/Resource/__tests__/Resource.spec.ts, nexus-sdk-js/src/Resource/index.ts, nexus-sdk-js/src/Resource/utils.ts
This fixes a problem where if you created a resource with an `@id` that is like a URL, for example `https://mywebsite.com`, it would not encode that URL when making the PUT request.
=> 👷‍♀️FIX: resource creation with URLs as IDs

nexus-sdk-js/src/Resource/index.ts, nexus-sdk-js/src/utils/__tests__/http.spec.ts, nexus-sdk-js/src/utils/http.ts
Because `Files` are now possible to fetch, we need to make the default for HTTP get to `Accept: application/json` otherwise when we try to list resources the SDK would fetch the actual files.
=> 👷‍♀️FIX: accept headers

package-lock.json, package.json, src/Resource/index.ts
Makes it possible to call getSelfAs as a static method, which is helpful when you want to fetch some graph data but you don't have an instance of Resource on hand.
=> 👷‍♀️FIX: add getSelfRawAs static Resource method

package-lock.json, package.json, src/Resource/__tests__/Resource.spec.ts, src/Resource/index.ts, src/Resource/types.ts, src/Resource/utils.ts
You now fetch resources in expanded formats
```typescript
const resource: Resource = await getResource(
'myorg',
'myproject',
'myschema',
'myresource',
{ expanded: true },
);
resource.expanded // true
```
You can also use the get self static method
```typescript
const r: Resource = await Resource.getSelf(
'http://myurl.com',
'myorg',
'myproject',
{ expanded: true },
);
```
=> Get Resource as Expanded

package-lock.json, package.json, src/Resource/__tests__/links.spec.ts, src/Resource/utils.ts, src/View/SparqlView/types.ts
The total results received from SPARQL queries are strings, so this small update makes sure we cast them as numbers to keep in like with `PaginationSettings` and `PaginatedList` typings.
=> 👷‍♀️FIX: fixify link pagination settings

package-lock.json, package.json, src/Organization/utils.ts, src/Project/utils.ts
Throw errors without changing their messages so web clients can make sense of bad requests
=> 👷‍♀️FIX: consistent error throwing

package-lock.json, package.json, src/View/utils.ts
Simply changes the get view method to throw the server response error instead of a custom one, which would incorrectly report `not found` when the error should have been `forbidden`. 
This will lead to less confusion in error reporting in nexus web.
=> 👷‍♀️FIX: view fetch error message

README.md, package-lock.json, package.json, src/Resource/__tests__/Resource.spec.ts, src/Resource/__tests__/__snapshots__/links.spec.ts.snap, src/Resource/__tests__/links.spec.ts, src/Resource/index.ts, src/Resource/types.ts, src/Resource/utils.ts
Fixes a problem where some links would be missing because of SPAQL shenanigans. 
Link methods now require as a param an expanded `@id` instead of the unresolved `@id` that you would normally get as a getByID response from the server. 
the instance methods to get links will fetch the expanded resource if it wasn't expanded already in order to get this expanded `@id`.
@julienmachon you will be happy to know that this resolves the missing links betwixt your inventory of Roux sauces.
=> 👷‍♀️FIX: expanded link ids

package-lock.json, package.json, src/Resource/__tests__/Resource.spec.ts, src/Resource/utils.ts
now when creating a resource instance with `Resource.getSelf` the sdk will check for the `files` path and parse the url correctly. Before this caused problems because file resources don't have schemas in their paths.
=> 👷‍♀️FIX: file path building

src/View/AggregateSparqlView/__tests__/__snapshots__/AggregateSparqlView.spec.ts.snap, src/View/ElasticSearchView/__tests__/ElasticSearchView.spec.ts, src/View/ElasticSearchView/index.ts, src/View/SparqlView/index.ts, src/View/__tests__/__snapshots__/utils.spec.ts.snap
myView.queryURL is now properly formatted with a uri-encoded `@id` that prevented queries to work on non-default views.
=> 👷‍♀️FIX: view query url

packages/nexus-sdk/src/nexusSdk.ts
For some reason, we overlooked to expose the `Resource` methods 🙀
=> 👷‍♀️FIX: expose resource methods

packages/nexus-sdk/src/View/types.ts
I'm checking with backend right now if we have to update this in order to support ES7 only, or if we have to support both. 
For ES7, the only change is:
```ts
{
total: {
relation: "eq" | "gte";
value: number;
}
}
```
=> 👷‍♀️FIX: proper ES response types

packages/nexus-sdk/src/Resource/index.ts, packages/nexus-sdk/src/Resource/types.ts
Fixes types for polling, listing, and getting so you can (optionally) do stuff like:
```typescript
type Person = { name: string };
const person = await nexus.Resource.get<Person>('org', 'proj', 'myId');
// Metadata types are still there
console.log(person["@id"]); // myId
// Won't throw an error!
console.log(person.name)
```
However, creating, updating, and deprecating a resource will always return the vanilla  `Resource` type because they just give back the metadata alone.
=> 👷‍♀️ FIX: change types for poll, list and get

apps/search-poc/src/containers/Header.tsx
changed the login button behavior to feel more natural. 
I was very upset that clicking on the button didn't do anything.
- if there are no realms, there is no button shown
- the first realm in the list is displayed as a default
- clicking on the button performs login
- hovering over the down arrow shows the realms
- clicking on a realm selects the realm
=> 👷‍♀️ FIX: login dropdown

apps/search-poc/src/components/ResourceDetails/EModel.tsx, apps/search-poc/src/components/ResourceDetails/__tests__/EModel.test.ts
Parse fitness property names with an optional leading underscore, eg: `_.Step_150.soma.v.AHP_depth`
=> Make leading underscore optional for fitness props

apps/search-poc/src/containers/ResultTable.tsx, apps/search-poc/src/views/MainView.tsx
We need to remove the withRouter and History from those containers/components that we want to wrap as web-components
=> Remove with router from ResultTable Container

apps/search-poc/src/containers/DashboardList.tsx, apps/search-poc/src/containers/Header.tsx, apps/search-poc/src/containers/ResultTable.tsx, apps/search-poc/src/utils/index.ts, apps/search-poc/src/utils/sparql.ts, apps/search-poc/src/web-components/web-component.ts, apps/search-poc/tslint.json, apps/search-poc/yarn.lock, package.json, tslint.json
Our monorepo linter would not run in the app directory, causing us to miss lint errors on push and causing headache when the build process would fail in jenkins that could have easily been avoided. 
- added the `apps/**` directory to the lint script. 
- fixed the 10 or so lint errors that were newly discovered. 
Now the linter is also ran during the pre-push commit hook, just before the tests
=> 👷‍♀️ FIX: prepush linter

apps/search-poc/package.json, apps/search-poc/src/components/Link.tsx, apps/search-poc/src/components/TabList.tsx, apps/search-poc/src/components/__tests__/Link.test.tsx, apps/search-poc/src/components/__tests__/__snapshots__/Link.test.tsx.snap, apps/search-poc/src/containers/DashboardList.tsx, apps/search-poc/src/containers/ResourceDetails/EModelCollection.tsx, apps/search-poc/src/containers/ResourceDetails/RecNrnMorphologyCollection.tsx, apps/search-poc/src/containers/ResourceDetails/ResourceDetails.tsx, apps/search-poc/src/containers/WorkspaceList.tsx, apps/search-poc/src/context/link.ts, apps/search-poc/src/history.ts, apps/search-poc/src/index.tsx, apps/search-poc/src/utils/__tests__/index.test.ts, apps/search-poc/src/utils/index.ts, apps/search-poc/src/views/DetailsView.tsx, apps/search-poc/src/views/MainView.tsx, apps/search-poc/src/web-components/build-config/template.html, apps/search-poc/src/web-components/resource-details/index.ts, apps/search-poc/src/web-components/studio-dashboard/index.ts, apps/search-poc/src/web-components/web-component.ts, apps/search-poc/yarn.lock
Now user interactions (clicks so far) will be handled in outer scope.
This way we can define custom logic for web components.
Current implementation will emit custom events when user clicks links
instead of changing current route
=> Add link component

apps/search-poc/package.json, apps/search-poc/yarn.lock
adds missing dep `react-shadow-dom-retarget-events` that blows up builds but not tests
the other changes are automatically added by yarn
=> 👷‍♀️ FIX: dependencies

packages/nexus-sdk/src/Resource/__tests__/resource.spec.ts, packages/nexus-sdk/src/Resource/index.ts, packages/nexus-sdk/src/Resource/types.ts
fixes https://github.com/BlueBrain/nexus/issues/760
While using `nexus.Resource.get`, the SDK will use the `Accept: application/json+ld` header so it will always fetch the resource metadata - even if it's a file
=> 👷‍♀️ FIX: use Accept json+ld Header in Resource.get method

packages/nexus-sdk/src/File/index.ts, packages/nexus-sdk/src/File/types.ts, packages/nexus-sdk/src/Project/index.ts, packages/nexus-sdk/src/Resource/index.ts, packages/nexus-sdk/src/Resource/types.ts, packages/nexus-sdk/src/View/index.ts
Reverts BlueBrain/nexus-js#279
This is not needed as ANY resource accepts those headers.
=> Revert "👷‍♀️FIX: getResourceOptions by adding getResourceCommonOptions"

packages/nexus-sdk/src/Resource/types.ts
I think these names are better because they match the API
=> Rename ResourceLink types

packages/nexus-sdk/src/Archive/__tests__/index.spec.ts, packages/nexus-sdk/src/Archive/index.ts, packages/nexus-sdk/src/Archive/types.ts
fixes a problem where the only possible Accept property was `text`, now it's possible to fetch archives with `json` (default) as `json` or `x-tar` as a blob
=> 👷‍♀️ FIX: Archive options

packages/nexus-sdk/src/Resource/__tests__/resource.spec.ts, packages/nexus-sdk/src/Resource/index.ts
Added an optional parameter to Resource.create to handle schema Id. When
it is present, create will make post call to the end point with
schema Id.
fixes BlueBrain/nexus/issues/788
=> Resource.create should pass schemaId

packages/nexus-sdk/src/Resource/__tests__/resource.spec.ts, packages/nexus-sdk/src/Resource/index.ts, packages/nexus-sdk/src/Resource/types.ts
Fixes BlueBrain/nexus#940
Updated `ResourceListOptions` with the new option:
```ts
sort?: string | string[];
```
=> Add sort type

packages/nexus-link/src/__tests__/links.spec.ts, packages/nexus-link/src/links.ts
Allows for users to catch errors using the `.subscribe()` API
=> add catchError to poll

yarn.lock
fixes HIGH warnings from `yarn audit`, mostly by upgrading `jest` and `lerna`. `yarn audit` still reports a MODERATE warning about `rollup-plugin-terser` but the maintainer hasn't released a patch to fix it yet.
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Arbitrary Code Execution                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.5.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of …
```
=> fix High warnings

packages/nexus-sdk/src/types.ts
I saw some code this weekend that finally gave me the answer of "how do I return the type that is returned by another function"
Here it is.
Please make sure it works properly!! Unit tests are not failing, which is great, but you should probably build and link locally (to nexus web) and make sure everything is still working fine.
=> Finally fixing this

packages/nexus-sdk/src/View/index.ts, packages/nexus-sdk/src/View/types.ts
Changes statistics methods return type from `PaginatedList<Statistics>` to `Statistics` and changed the `Statistics` type to include possible `CompositeView` values collection property
=> Fix statistics type (no longer collection)

packages/nexus-sdk/README.md, packages/nexus-sdk/src/__tests__/nexusSDK.spec.ts, packages/nexus-sdk/src/nexusSdk.ts
This property overwrite the links used to generate the requestHandler, so that they can have full control over the links queue for things like caching and parsing.
=> add linksOverwrite property to createNexusClient options

packages/nexus-link/yarn.lock, packages/nexus-sdk/yarn.lock, packages/react-nexus/yarn.lock, yarn.lock
This reverts commit d7cad0b75394629704e08080f229fefcd3a45515.
The above commits updates a bunch of packages. It also causes inconsistencies in packages/nexus-sdk/yarn.lock, and when ever you run make build, yarn.lock is modified. This in turn causes publish command to fail due to "uncommitted changes" error.
As the first step towards a solution, we revert the commit. We will fix the vulnerable packages in a later commit.
=> Revert "chore: fix vulerable packages (#328)"

packages/nexus-sdk/src/File/__tests__/File.spec.ts, packages/nexus-sdk/src/File/index.ts, packages/nexus-sdk/src/File/types.ts, packages/nexus-sdk/src/Resolver/__tests__/resolver.spec.ts, packages/nexus-sdk/src/Resolver/index.ts, packages/nexus-sdk/src/Resolver/types.ts, packages/nexus-sdk/src/Resource/__tests__/resource.spec.ts, packages/nexus-sdk/src/Resource/index.ts, packages/nexus-sdk/src/Resource/types.ts, packages/nexus-sdk/src/Schema/__tests__/schema.spec.ts, packages/nexus-sdk/src/Schema/index.ts, packages/nexus-sdk/src/Schema/types.ts, packages/nexus-sdk/src/Storage/__tests__/storage.spec.ts, packages/nexus-sdk/src/Storage/index.ts, packages/nexus-sdk/src/Storage/types.ts, packages/nexus-sdk/src/View/__tests__/view.spec.ts, packages/nexus-sdk/src/View/index.ts, packages/nexus-sdk/src/View/types.ts, packages/nexus-sdk/src/types.ts
Fixes https://github.com/BlueBrain/nexus/issues/1395
indexing=sync|async
The parameter will default to sync if not specified.
=> Add consistent writes support via the indexing parameter to methods that support it

packages/nexus-link/package.json, packages/nexus-sdk/package.json, packages/nexus-sdk/src/Resource/README.md, packages/nexus-sdk/src/Resource/__tests__/resource.spec.ts, packages/nexus-sdk/src/Resource/index.ts, packages/react-nexus/package.json
Resources endpoint now supports listing resources within specific project (which was already implemented), within an organization and across all organisations.This change supports the latter two methods.
For listing resources within a specific organization:
GET /v1/resources/{org_label}?from={from}
&size={size}
&deprecated={deprecated}
&rev={rev}
&type={type}
&createdBy={createdBy}
&updatedBy={updatedBy}
&schema={schema}
&q={search}
&sort={sort}
For listing resources across all organizations/projects:
GET /v1/resources?from={from}
&size={size}
&deprecated={deprecated}
&rev={rev}
&type={type}
&createdBy={createdBy}
&updatedBy={updatedBy}
&schema={schema}
&q={search}
&sort={sort}
=> Support new endpoints for listing Resources across all orgs/projects or just specific a org

packages/nexus-link/package.json, packages/nexus-sdk/package.json, packages/nexus-sdk/src/View/__tests__/view.spec.ts, packages/nexus-sdk/src/View/index.ts, packages/react-nexus/package.json
Fixes https://github.com/BlueBrain/nexus/issues/3012
Put paging options (size and from) into body of request rather than as query params which seem to get ignored.
=> 3012 paging not working for es
