- nexus-sdk-js/src/Nexus.ts
> Smal tweeks

- nexus-sdk-js/README.md
- nexus-sdk-js/package.json
- nexus-sdk-js/src/Nexus.ts
- nexus-sdk-js/src/Organization.ts
- nexus-sdk-js/src/Project.ts
- Update licence, package name and version
- Add a super simple *get started* code example
- implement `listOrganizations`, `getOrganization`, `listPorjects` and `getProject`
> v0.0.1 is ready 💥

- nexus-sdk-js/package-lock.json
- nexus-sdk-js/package.json
- nexus-sdk-js/src/Nexus.ts
- nexus-sdk-js/src/Organization.ts
- nexus-sdk-js/src/Project.ts
- nexus-sdk-js/src/__tests__/Project.spec.ts
Organisations now have a `projectNumber` property and Projects have a `resourceNumber` property.
> grabbing all the numberzz

- nexus-sdk-js/README.md
- nexus-sdk-js/package-lock.json
- nexus-sdk-js/package.json
- nexus-sdk-js/rollup.config.js
- nexus-sdk-js/src/Nexus.ts
- nexus-sdk-js/src/Organization/__tests__/Oragnization.spec.ts
- nexus-sdk-js/src/Organization/exceptions.ts
- nexus-sdk-js/src/Organization/index.ts
- nexus-sdk-js/src/__mocks__/helpers.ts
- nexus-sdk-js/src/__tests__/Nexus.spec.ts
- nexus-sdk-js/src/__tests__/Project.spec.ts
- nexus-sdk-js/src/__tests__/__snapshots__/Nexus.spec.ts.snap
- nexus-sdk-js/src/index.ts
- nexus-sdk-js/src/utils/http.ts
- nexus-sdk-js/test/helpers.ts
- nexus-sdk-js/test/setupJest.js
- nexus-sdk-js/tsconfig.json
You can now create organisations! Whoop!
> 326 create orgs

- nexus-sdk-js/Makefile
- nexus-sdk-js/README.md
- nexus-sdk-js/docker-compose.yaml
- nexus-sdk-js/package-lock.json
- nexus-sdk-js/package.json
- nexus-sdk-js/rollup.config.js
- nexus-sdk-js/tsconfig.json
Path to UMD lib was not correct. I've also added a compose file so we can run/test/compile the SDK with any versions of node easily. This can also be useful for people that don't have node installed locally.
> Fix umd lib directory and more

- nexus-sdk-js/package-lock.json
- nexus-sdk-js/package.json
- nexus-sdk-js/rollup.config.js
- nexus-sdk-js/src/Nexus.ts
- nexus-sdk-js/src/index.ts
- nexus-sdk-js/src/store.ts
- nexus-sdk-js/src/utils/http.ts
- nexus-sdk-js/tsconfig.json
I'm now using the official typescript plugin for building an browser version of the SDK. 
Tested on my Mac and Linux workstation, all building and running fine.
> fix umd build

- nexus-sdk-js/README.md
- nexus-sdk-js/rollup.config.js
- nexus-sdk-js/src/Nexus.ts
- nexus-sdk-js/src/Organization/index.ts
- nexus-sdk-js/src/Organization/utils.ts
- nexus-sdk-js/src/Project/index.ts
- nexus-sdk-js/src/Project/utils.ts
- nexus-sdk-js/src/Resource/__tests__/Resource.spec.ts
- nexus-sdk-js/src/Resource/index.ts
- nexus-sdk-js/src/Resource/utils.ts
- nexus-sdk-js/src/__tests__/Nexus.spec.ts
- nexus-sdk-js/src/index.ts
- nexus-sdk-js/src/store.ts
- nexus-sdk-js/src/utils/http.ts
- nexus-sdk-js/src/views/ElasticSearchView/index.ts
I went down the rabbit hole a little bit with that one, but the `README` shows why (static methods)
> refactor static methods

- nexus-sdk-js/README.md
- nexus-sdk-js/src/Project/index.ts
- nexus-sdk-js/src/Project/types.ts
- nexus-sdk-js/src/Project/utils.ts
you can now create project (there was also some nasty merge conflict in the readme...)
> Implement create project

- nexus-sdk-js/README.md
- nexus-sdk-js/package-lock.json
- nexus-sdk-js/src/Organization/__tests__/Oragnization.spec.ts
- nexus-sdk-js/src/Organization/index.ts
- nexus-sdk-js/src/Organization/utils.ts
- nexus-sdk-js/src/__tests__/__snapshots__/Nexus.spec.ts.snap
- nexus-sdk-js/src/utils/http.ts
You can now:
- get a specific org revision/tag
- update an org's name
- deprecate an org
- pass list orgs options (blocked by BlueBrain/nexus#112 thought)
- tag an organization
> Finish orgs

- nexus-sdk-js/README.md
- nexus-sdk-js/src/Project/__tests__/Project.spec.ts
- nexus-sdk-js/src/Project/index.ts
- nexus-sdk-js/src/Project/types.ts
- nexus-sdk-js/src/Project/utils.ts
- nexus-sdk-js/src/__tests__/__snapshots__/Nexus.spec.ts.snap
- nexus-sdk-js/src/utils/http.ts
- nexus-sdk-js/tsconfig.json
you can now:
- get a specific project revision/tag
- update a project's name
- deprecate a project
- pass list project options (blocked by BlueBrain/nexus#112 thought)
- tag a project
> Finish projects

- nexus-sdk-js/package-lock.json
- nexus-sdk-js/package.json
- nexus-sdk-js/src/Organization/__tests__/Organization.spec.ts
- nexus-sdk-js/src/Organization/utils.ts
- nexus-sdk-js/src/Project/__tests__/Project.spec.ts
- nexus-sdk-js/src/Project/utils.ts
- nexus-sdk-js/src/utils/__tests__/http.spec.ts
- nexus-sdk-js/src/utils/http.ts
- nexus-sdk-js/src/views/ElasticSearchView/__tests__/ElasticSearchView.spec.ts
If we don't get a 2xx back from the API, this means we get an "error". In this situation, we now reject the Promise
> Reject none 2xx

- nexus-sdk-js/package.json
- nexus-sdk-js/src/Project/__tests__/Project.spec.ts
- nexus-sdk-js/src/Project/types.ts
you can create or modify a project with only `name` in the payload.
> only name is required

- nexus-sdk-js/src/View/index.ts
cannot export TS interfaces as they don't exists after transpiling the code
> no TS specific export

- nexus-sdk-js/src/Realm/__mocks__/mockReponses.ts
- nexus-sdk-js/src/Realm/__tests__/Realm.spec.ts
- nexus-sdk-js/src/Realm/index.ts
- nexus-sdk-js/src/Realm/types.ts
- nexus-sdk-js/src/Realm/utils.ts
- nexus-sdk-js/src/index.ts
- nexus-sdk-js/src/utils/types.ts
You can now list and get Realms
`Realm.get(realmLabel)` and `Realm.list(listOptions?)`
> Realms implementation

- nexus-sdk-js/src/Nexus.ts
- nexus-sdk-js/src/Organization/__tests__/Organization.spec.ts
- nexus-sdk-js/src/Organization/index.ts
- nexus-sdk-js/src/Organization/types.ts
- nexus-sdk-js/src/Organization/utils.ts
- nexus-sdk-js/src/Project/index.ts
- nexus-sdk-js/src/Project/types.ts
- nexus-sdk-js/src/Project/utils.ts
- nexus-sdk-js/src/Realm/utils.ts
- nexus-sdk-js/src/Resource/__tests__/Resource.spec.ts
- nexus-sdk-js/src/Resource/index.ts
- nexus-sdk-js/src/Resource/types.ts
- nexus-sdk-js/src/Resource/utils.ts
- nexus-sdk-js/src/View/ElasticSearchView/index.ts
- nexus-sdk-js/src/View/ElasticSearchView/types.ts
- nexus-sdk-js/src/View/SparqlView/index.ts
- nexus-sdk-js/src/View/SparqlView/types.ts
- nexus-sdk-js/src/View/utils.ts
- nexus-sdk-js/src/__mocks__/helpers.ts
- nexus-sdk-js/src/__tests__/Nexus.spec.ts
- nexus-sdk-js/src/utils/types.ts
Ok, I've made every `list()` a paginated result. I've also added an index, so we know if we're on page 1 or x
> Paginated orgs and project

- nexus-sdk-js/README.md
- nexus-sdk-js/src/Resource/utils.ts
- nexus-sdk-js/src/Schema/__mocks__/mockSchemaResponses.ts
- nexus-sdk-js/src/Schema/__tests__/Schema.spec.ts
- nexus-sdk-js/src/Schema/__tests__/__snapshots__/Schema.spec.ts.snap
- nexus-sdk-js/src/Schema/index.ts
- nexus-sdk-js/src/Schema/types.ts
- nexus-sdk-js/src/Schema/utils.ts
> Implement schema

- nexus-sdk-js/README.md
update todo + function signatures
> mark SSE support as experimental

- nexus-sdk-js/package-lock.json
- nexus-sdk-js/package.json
- nexus-sdk-js/src/Resource/__tests__/Resource.spec.ts
- nexus-sdk-js/src/Resource/index.ts
- nexus-sdk-js/src/Resource/types.ts
- nexus-sdk-js/src/Resource/utils.ts
Simply makes the context input for updates match the context type used elsewhere in Resource
ALSO provides a fix for the resource path to make sure the ID is URL encoded
> 👷‍♀️FIX:  resource update context input

- nexus-sdk-js/package-lock.json
- nexus-sdk-js/package.json
- nexus-sdk-js/tslint.prod.json
you can't push broken code anymore (unless you force it :grimacing: )
> Add pre-push hooks

- nexus-sdk-js/README.md
- nexus-sdk-js/package-lock.json
- nexus-sdk-js/package.json
- nexus-sdk-js/src/File/__tests__/__snapshots__/file.spec.ts.snap
- nexus-sdk-js/src/File/__tests__/file.spec.ts
- nexus-sdk-js/src/File/index.ts
- nexus-sdk-js/src/File/types.ts
- nexus-sdk-js/src/File/utils.ts
- nexus-sdk-js/src/Project/index.ts
- nexus-sdk-js/src/Resource/utils.ts
- nexus-sdk-js/src/View/SparqlView/index.ts
- nexus-sdk-js/src/index.ts
- nexus-sdk-js/src/utils/__tests__/http.spec.ts
- nexus-sdk-js/src/utils/http.ts
- nexus-sdk-js/src/utils/index.ts
- nexus-sdk-js/test/setupJest.js
> File.Create()

- package-lock.json
- package.json
- src/Resource/__tests__/Resource.spec.ts
- src/Resource/index.ts
- src/Resource/types.ts
- src/Resource/utils.ts
- src/__mocks__/helpers.ts
1. Get a resource
```typescript
const resource = new Resource(
'testOrg',
'testProject',
resourceResponse,
);
```
2. Fetch that resource's raw data in a certain `format`
```typescript
// As JSON_LD (myResourceResponse is parsed into JS object)
const myResourceResponse = await resource.getAs(
ResourceGetFormat.JSON_LD,
);
const myID = myResourceResponse["@id"];
// As DOT notation
const myResourceResponse = await resource.getAs(
ResourceGetFormat.DOT,
);
// digraph {
//  "someValue" -> "9.223E0" [label = "http://schema.org/height"] ...
// As nTriples
const myResourceResponse = await resource.getAs(
ResourceGetFormat.N_TRIPLES,
);
// _:6bb65725-b0ca-40be-b5c9-56b8dd394401 <https://bluebrain.github.io/nexus/vocabulary/algorithm> "SHA-256" 
```
> Resource Content Negotiation

- package-lock.json
- package.json
- src/File/__tests__/file.spec.ts
- src/File/utils.ts
- src/utils/http.ts
- src/utils/index.ts
Addresses a problem where images would fail to load in Nexus web.
Fix new requirement from API to always provide Accept header
Add tests to make sure `*/*` is given when fetching file.
> 👷‍♀️FIX: file header and test to make sure Accept is always provided

- Jenkinsfile
- README.md
- package-lock.json
- package.json
> Add codecov

- package-lock.json
- package.json
> fix: TSLint warning due to error on their side

- README.md
- package-lock.json
- package.json
- src/File/__tests__/file.spec.ts
- src/File/utils.ts
- src/Resource/__tests__/Resource.spec.ts
- src/Resource/__tests__/__snapshots__/links.spec.ts.snap
- src/Resource/__tests__/links.spec.ts
- src/Resource/index.ts
- src/Resource/types.ts
- src/Resource/utils.ts
- src/View/ElasticSearchView/index.ts
list resources that have a relationship to this entity!
```typescript
// Links! 🔗🔗🔗🔗
const incomingLinks: PaginatedList<ResourceLinks> = await resourceInstance.getIncomingLinks({ from: 0, size: 20}: PaginationSettings);
const outgoingLinks: PaginatedList<ResourceLinks> = await resourceInstance.getOutgoingLinks({ from: 0, size: 20}: PaginationSettings);
/*
{
...paginationSettings,
results: [{
link: Resource | string, // Resource or URL
isExternal: boolean, // does this resource exist on the platform, or a link to somewhere?
predicate:  "https://myNexusInstance.com/vocabs/myOrg/friendProject/friend" // URL vocab link 
}]
}
*/
```
> Incoming / Outgoing Links

- package-lock.json
- package.json
- src/Resource/__tests__/__snapshots__/links.spec.ts.snap
- src/Resource/index.ts
- src/Resource/utils.ts
Improves incoming and outgoing link queries so that
- `_self` is no longer attributed as an incoming link
- nested properties with links are now included as outgoing links
> 👷‍♀️FIX: link queries improvements

- .gitignore
- Makefile
- README.md
- docker-compose.yaml
- package-lock.json
A nice way of getting a Node.js environment with docker. The main benifit now is that the container will run as "you", so no more outputs created under `root`
> add dshell target in makefile

- src/View/AggregateSparqlView/__tests__/AggregateSparqlView.spec.ts
- src/View/AggregateSparqlView/__tests__/__snapshots__/AggregateSparqlView.spec.ts.snap
- src/View/AggregateSparqlView/index.ts
- src/View/AggregateSparqlView/types.ts
- src/View/SparqlView/types.ts
- src/View/index.ts
For all your aggregated sparql query needs
```typescript
const aggregateSparqlView = new AggregateSparqlView(
'myOrg',
'myProject',
mockAggregatedSparqlViewGetResponse,
);
```
> ✨ FEAT: AggregateSparqlView class

- package-lock.json
- package.json
- src/ACL/utils.ts
- src/File/__tests__/file.spec.ts
- src/File/index.ts
- src/File/utils.ts
- src/Nexus.ts
- src/Organization/utils.ts
- src/Project/utils.ts
- src/Realm/utils.ts
- src/Resolver/utils.ts
- src/Resource/utils.ts
- src/Schema/utils.ts
- src/View/ElasticSearchView/index.ts
- src/utils/types.ts
- makes NexusFiles compliant to the new nexus class signature so we can use multiple instances server side and the like. 
- changes all the paginationSetting defaults from 1 to 0
- npm audit fixed
> 👷‍♀️FIX: makeFileUtils

- package-lock.json
- package.json
our package versions were out of sync from releases
> 👷‍♀️ FIX: make package version beta 21

- src/Resource/__tests__/Resource.spec.ts
- src/Resource/index.ts
- src/Resource/utils.ts
- src/View/ElasticSearchView/__tests__/ElasticSearchView.spec.ts
- src/__mocks__/helpers.ts
- src/__tests__/Nexus.spec.ts
> fix(Resource): Always get a resolvable id as @id

- packages/nexus-sdk/src/ACL/index.ts
- packages/nexus-sdk/src/File/__tests__/File.spec.ts
- packages/nexus-sdk/src/File/index.ts
- packages/nexus-sdk/src/Identity/index.ts
- packages/nexus-sdk/src/Organization/index.ts
- packages/nexus-sdk/src/Permissions/index.ts
- packages/nexus-sdk/src/Project/index.ts
- packages/nexus-sdk/src/Realm/index.ts
- packages/nexus-sdk/src/Resolver/index.ts
- packages/nexus-sdk/src/Resource/index.ts
- packages/nexus-sdk/src/Schema/index.ts
- packages/nexus-sdk/src/Storage/index.ts
- packages/nexus-sdk/src/View/index.ts
- packages/nexus-sdk/src/nexusSdk.ts
- packages/nexus-sdk/src/types.ts
> move toPromise() at method level

- packages/nexus-link/src/links.ts
- packages/nexus-sdk/src/nexusSdk.ts
Fix a problem where the wrong method would be applied to a fetch operation
> 👷‍♀️FIX: pass method to fetch

- lerna.json
- packages/nexus-link/package.json
- packages/nexus-sdk/package.json
> bump version

- packages/nexus-sdk/src/Organization/__tests__/organization.spec.ts
- packages/nexus-sdk/src/Organization/types.ts
- packages/nexus-sdk/src/Project/__tests__/project.spec.ts
- packages/nexus-sdk/src/Project/types.ts
- packages/nexus-sdk/src/Resource/__tests__/resource.spec.ts
- packages/nexus-sdk/src/Resource/types.ts
now allows for `q=myTextSearch` while listing KG resources and `label=myProjectOrOrg` while listing projects or orgs
> ✨FEAT: add admin and kg new filter features

- packages/nexus-link/package.json
- packages/nexus-sdk/package.json
- packages/react-nexus/package.json
- packages/react-nexus/src/AccessControl.tsx
> 👷‍♀️ FIX: add watch script + render actual children rather than string 🤦‍♂️

- packages/nexus-sdk/src/Organization/types.ts
- packages/nexus-sdk/src/Project/types.ts
- packages/react-nexus/README.md
- packages/react-nexus/src/useNexus.tsx
you can now call use nexus like a useEffect hook to reload its values based on some input array. 
also added a missing type from `Project`
export `OrgResponseCommon` and `ProjectResponseCommon`
> 👷‍♀️ FIX: add useEffect input param to reload useNexus

- .gitignore
- packages/nexus-link/src/links.ts
- packages/nexus-sdk/src/ACL/index.ts
- packages/nexus-sdk/src/File/__tests__/File.spec.ts
- packages/nexus-sdk/src/File/index.ts
- packages/nexus-sdk/src/Identity/__tests__/identity.spec.ts
- packages/nexus-sdk/src/Identity/index.ts
- packages/nexus-sdk/src/Organization/__tests__/organization.spec.ts
- packages/nexus-sdk/src/Organization/index.ts
- packages/nexus-sdk/src/Permissions/index.ts
- packages/nexus-sdk/src/Project/__tests__/project.spec.ts
- packages/nexus-sdk/src/Project/index.ts
- packages/nexus-sdk/src/Realm/__tests__/realm.spec.ts
- packages/nexus-sdk/src/Realm/index.ts
- packages/nexus-sdk/src/Resolver/__tests__/resolver.spec.ts
- packages/nexus-sdk/src/Resolver/index.ts
- packages/nexus-sdk/src/Resolver/types.ts
- packages/nexus-sdk/src/Schema/index.ts
- packages/nexus-sdk/src/Schema/types.ts
- packages/nexus-sdk/src/View/__tests__/view.spec.ts
- packages/nexus-sdk/src/View/index.ts
- packages/nexus-sdk/src/nexusSdk.ts
- packages/nexus-sdk/src/types.ts
- packages/react-nexus/package.json
- packages/react-nexus/src/useNexus.tsx
with this change, we can do things like:
```typescript
const state = useNexus<Statistics>((nexus: NexusClient) =>
nexus.View.pollStatistics(
props.orgLabel,
props.projectLabel,
props.resourceId,
{ pollTime: 3000 }
)
```
> add Observable support for useNexus and create pollStatistics method

- packages/nexus-sdk/src/Resource/index.ts
- packages/nexus-sdk/src/Resource/types.ts
- packages/nexus-sdk/src/constants/index.ts
- packages/nexus-sdk/src/index.ts
constants for default IDs as mentioned here: https://github.com/BlueBrain/nexus-sdk-js/pull/185#issuecomment-507282092
> ✨ FEAT: add constants for views and schema IDs

- packages/nexus-sdk/src/Resource/index.ts
- packages/nexus-sdk/src/constants/index.ts
change default names so as not to import the entire list of default values every time 🤦‍♀️
> 👷‍♀️ FIX: default names

- packages/nexus-sdk/src/Resolver/types.ts
- packages/nexus-sdk/src/Schema/types.ts
- packages/nexus-sdk/src/Storage/types.ts
`@id` is optional in a Resource payload
> make @id available and optional for all resources types

- packages/nexus-sdk/src/Resource/README.md
- packages/nexus-sdk/src/Resource/__tests__/resource.spec.ts
- packages/nexus-sdk/src/Resource/index.ts
Adds an api method for the `incoming` and `outgoing` resource link listing
> ✨ FEAT: add listing resource links

- apps/search-poc/src/utils/sparql.ts
List self urls instead of `@id`s
> 👷‍♀️ Fix: list self urls

- apps/search-poc/package.json
- apps/search-poc/src/components/Results.tsx
- apps/search-poc/src/index.tsx
- apps/search-poc/src/views/Details.tsx
- apps/search-poc/yarn.lock
Adds two examples of `ReconstructedNeuronMorphologies` 
one from `pgetta`'s scripts
one from `bbp/nmc`
> Add simple list with example Resources

- apps/search-poc/src/components/Header.tsx
- apps/search-poc/src/components/ResourceDetails.css
- apps/search-poc/src/components/ResourceDetails.tsx
- apps/search-poc/src/containers/ResourceDetails.tsx
- apps/search-poc/src/index.css
Some simple style improvements to the whole app, header, and the simple ResourceDetails Component
> Style improvements

- apps/search-poc/src/components/DashboardList.tsx
- apps/search-poc/src/config.ts
- apps/search-poc/src/containers/DashboardList.tsx
- apps/search-poc/src/views/Main.tsx
Fixes a bug where history.push would be called infinitely causing my poor browser to explode. 
- Pushes router logic to the View 
- ActiveDashboardId now passed to component from View from query string
- no more infinite rendering / memory leaking / loops! ✨
> 👷‍♀️ FIX: history reload bug

- apps/search-poc/src/components/ResourceDetails/ResourceDetails.css
- apps/search-poc/src/components/ResourceDetails/ResourceDetails.tsx
- apps/search-poc/src/containers/ResourceDetails/ResourceDetails.tsx
- apps/search-poc/src/containers/ResourceDetails/types.ts
Add:
* brainRegion
* species
* strain
* layers
> Extend common resource details

- apps/search-poc/README.md
- apps/search-poc/src/components/ResultTable.tsx
- update README to include new example queries
- remove "Identifier" default property in Results table
> Update query properties

- apps/search-poc/src/components/ResultTable.css
- apps/search-poc/src/components/ResultTable.tsx
> Refactor css for result table

- apps/search-poc/scripts/createStudio.js
- apps/search-poc/scripts/resources.js
- package.json
- tsconfig.json
- yarn.lock
Added workspaces as described in the "Dashboards Query" document. 
- Thalamus 2019
- SSCx 2019
- BBP Overview
> update scripts to work with multiple workspaces

- apps/search-poc/package.json
- apps/search-poc/src/web-components/resource-details/readme.md
- apps/search-poc/src/web-components/resource-details/template.html
- apps/search-poc/src/web-components/resource-details/webpack.config.common.js
- apps/search-poc/src/web-components/resource-details/webpack.config.dev.js
- apps/search-poc/src/web-components/resource-details/webpack.config.prod.js
- apps/search-poc/yarn.lock
> Add resource details web component dev setup and documentation

- apps/search-poc/enzyme.d.ts
- apps/search-poc/src/setupTests.ts
- Deleted a wrong file by mistake in previous PR. Correcting it here.
> Delete type declaration/add SetUpTests

- apps/search-poc/src/components/TabList.css
- apps/search-poc/src/components/TabList.tsx
- apps/search-poc/src/containers/WorkspaceList.tsx
- apps/search-poc/src/views/MainView.css
- apps/search-poc/src/views/MainView.tsx
> reorient workspace list

- packages/nexus-link/src/__tests__/links.spec.ts
Added simple unit tests for Links setToken and setMethod.
> Added tests for setToken and setMethod

- apps/search-poc/scripts/createStudio.js
- apps/search-poc/scripts/resources.js
fixes a problem where instead of one studio being created, a studio would be created for each workspace.
> 👷‍♀️ FIX: duplicate studios

- apps/search-poc/src/hooks/useMorphology.ts
- apps/search-poc/yarn.lock
- package.json
- packages/react-nexus/package.json
- packages/react-nexus/yarn.lock
- yarn.lock
Fixes an error where react would complain about multiple instances of react found within the search-app when launched. 
[solution here](https://github.com/react-static/react-static/issues/1216)
> 👷‍♀️ FIX:  duplicate react error

- packages/nexus-sdk/src/Resource/types.ts
fixes: https://github.com/BlueBrain/nexus/issues/759
> 👷‍♀️ FIX: add generic type to resources

- packages/nexus-sdk/src/Resource/types.ts
fixes: https://github.com/BlueBrain/nexus/issues/768
> 👷‍♀️ FIX: rename total to _total in Resource/PaginatedResource

- packages/nexus-sdk/src/File/index.ts
- packages/nexus-sdk/src/Resolver/types.ts
- packages/nexus-sdk/src/Resource/index.ts
- packages/nexus-sdk/src/Resource/types.ts
- packages/nexus-sdk/src/Schema/types.ts
- packages/nexus-sdk/src/Storage/types.ts
- packages/nexus-sdk/src/View/types.ts
fixes https://github.com/BlueBrain/nexus/issues/763
> 👷‍♀️ FIX: add ResourceLink type

- packages/nexus-sdk/README.md
- packages/nexus-sdk/src/nexusSdk.ts
- packages/nexus-sdk/src/utils.ts
Implements https://github.com/BlueBrain/nexus/issues/754
> 754 use default fetch

- packages/nexus-sdk/src/Resource/index.ts
- packages/nexus-sdk/src/Resource/types.ts
fixes https://github.com/BlueBrain/nexus/issues/771
> Add ExpandedResource type

- lerna.json
- packages/nexus-link/package-lock.json
- packages/nexus-link/package.json
- packages/nexus-sdk/package-lock.json
- packages/nexus-sdk/package.json
- packages/react-nexus/package-lock.json
- packages/react-nexus/package.json
https://github.com/BlueBrain/nexus-js/releases/tag/untagged-0c2895d4e0afaf4c3892
> new version

- lerna.json
- packages/nexus-link/package-lock.json
- packages/nexus-link/package.json
- packages/nexus-sdk/package-lock.json
- packages/nexus-sdk/package.json
- packages/react-nexus/package-lock.json
- packages/react-nexus/package.json
> version v1.2.1 bump

- lerna.json
- packages/nexus-sdk/src/Version/_tests_/version.spec.ts
- packages/nexus-sdk/src/Version/index.ts
- packages/nexus-sdk/src/Version/index.tsx
- packages/nexus-sdk/src/Version/types.ts
- packages/nexus-sdk/src/nexusSdk.ts
Fixes BlueBrain/nexus#1005
- Adds a method to get the service Version
- Adds Version type
> Add Version get

- packages/nexus-sdk/src/View/__tests__/view.spec.ts
- packages/nexus-sdk/src/View/index.ts
implements: https://github.com/BlueBrain/nexus/issues/1004
> View.restart()

- lerna.json
> Version update

- packages/nexus-sdk/src/View/__tests__/view.spec.ts
- packages/nexus-sdk/src/View/index.ts
- packages/nexus-sdk/src/View/types.ts
Add types and end points for composite view support.
Fixes BlueBrain/nexus/issues/1007
Integ test set up : https://gist.github.com/dhaneshnm/8240e2b80ec5abc1293ff306bb9caeca
> Add Composite  View support

- packages/nexus-sdk/src/View/types.ts
"@id" was added by mistake earlier.
> update id to type fix CompositeView type defintion

- packages/react-nexus/src/NexusProvider.tsx
Simple PR for removing the dirty `any` of the provider's props.
> add props types

- packages/nexus-link/src/__tests__/links.spec.ts
- packages/nexus-link/src/links.ts
- packages/nexus-link/src/types.ts
- packages/nexus-sdk/src/nexusSdk.ts
- scripts/setupJest.ts
triggeringFetch and parsing the response now split into two separate links to enable things like caching.
> Feat nexus link parse response

- packages/nexus-link/yarn.lock
- packages/nexus-sdk/yarn.lock
- packages/react-nexus/yarn.lock
- yarn.lock
ran `npx yarn-audit-fix` in packages / monorepo
> chore: fix vulerable packages

- packages/nexus-link/src/__tests__/links.spec.ts
- packages/nexus-link/src/links.ts
Remove abort controller logic from triggerFetch link
> Remove abort controller

- packages/nexus-sdk/src/Archive/README.md
- packages/nexus-sdk/src/File/README.md
- packages/nexus-sdk/src/Identity/README.md
- packages/nexus-sdk/src/Organization/README.md
- packages/nexus-sdk/src/Permissions/README.md
- packages/nexus-sdk/src/Project/README.md
- packages/nexus-sdk/src/Realm/README.md
- packages/nexus-sdk/src/Resolver/README.md
- packages/nexus-sdk/src/Resource/README.md
- packages/nexus-sdk/src/Schema/README.md
- packages/nexus-sdk/src/Storage/README.md
- packages/nexus-sdk/src/View/README.md
- Fixes outdated links in the SDK documentation.
> Fix out dated links in documentation

- packages/nexus-sdk/src/Resource/index.ts
- packages/nexus-sdk/src/Resource/types.ts
- packages/nexus-sdk/src/constants/index.ts
Changes to match the delta v1.5.
> Change type definition for ExpandedResource

- packages/nexus-link/package.json
- packages/nexus-sdk/package.json
- packages/react-nexus/package.json
> bump version to 1.3.5

- packages/nexus-sdk/src/Search/__tests__/search.spec.ts
- packages/nexus-sdk/src/Search/index.ts
- support search/config and search/query end points.
> support delta search enpoints

- packages/nexus-sdk/src/nexusSdk.ts
> Add end point to the SDK

- packages/nexus-link/package.json
- packages/nexus-sdk/package.json
- packages/react-nexus/package.json
> Bump version to 1.3.6

- packages/nexus-sdk/package.json
- packages/nexus-sdk/src/Project/README.md
- packages/nexus-sdk/src/Project/__tests__/project.spec.ts
- packages/nexus-sdk/src/Project/index.ts
- packages/nexus-sdk/src/Project/types.ts
- packages/nexus-sdk/src/Quotas/README.md
- packages/nexus-sdk/src/Quotas/__tests__/quotas.spec.ts
- packages/nexus-sdk/src/Quotas/index.ts
- packages/nexus-sdk/src/Quotas/types.ts
- packages/nexus-sdk/src/nexusSdk.ts
Part of BlueBrain/nexus#2525
- Adds `quotas` endpoint to get projects quotas
- Adds `statistics` endpoint to projects
> Support quota endpoints

- packages/nexus-link/package.json
- packages/nexus-sdk/package.json
- packages/nexus-sdk/src/Storage/__tests__/storage.spec.ts
- packages/nexus-sdk/src/Storage/index.ts
- packages/nexus-sdk/src/Storage/types.ts
- packages/react-nexus/package.json
- adds `/statistics` endpoint to `storages`
- updates types
> Update storages endpoints

- package-lock.json
- packages/nexus-link/package.json
- packages/nexus-sdk/package.json
- packages/nexus-sdk/src/Project/README.md
- packages/nexus-sdk/src/Project/__tests__/project.spec.ts
- packages/nexus-sdk/src/Project/index.ts
- packages/nexus-sdk/src/Project/types.ts
- packages/react-nexus/package.json
Part of BlueBrain/nexus#2772
The Delta API exposes the project deletion configuration as follows:
```
{
"@context": "https://bluebrain.github.io/nexus/contexts/project-deletion.json",
"@type": "ProjectDeletionConfig",
"_idleIntervalInSeconds": 600,
"_idleCheckPeriodInSeconds": 5,
"_deleteDeprecatedProjects": true,
"_includedProjects": [
"some.+"
],
"_excludedProjects": [
".+"
]
}
```
Notice the fields `_includedProjects` and `_excludedProjects`. These define a collection of regexes that select and filter out the projects that are to be automatically deleted.
> 2710 project deletion config endpoint

- packages/nexus-sdk/src/Resource/__tests__/resource.spec.ts
- packages/nexus-sdk/src/Resource/index.ts
- packages/nexus-sdk/src/Resource/types.ts
Required for https://github.com/BlueBrain/nexus/issues/2709 where resource revisions also show any associated tags
> Support fetching tags of a resource

- packages/nexus-link/package.json
- packages/nexus-sdk/package.json
- packages/nexus-sdk/src/Resource/README.md
- packages/react-nexus/package.json
> Bump version to 1.3.11

- packages/nexus-sdk/src/Resource/__tests__/resource.spec.ts
- packages/nexus-sdk/src/Resource/index.ts
Adds support for removing a tag from a resource
> Support removing tag from resource
